/**
 * Gom Don API
 * Gom Don API.
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface BuyModelUpdateData { 
    gomdon_status?: number;
    /**
     * Số lượng thực tế nhận được
     */
    actual_quantity?: number;
    /**
     * Lấy từ bảng sản phẩm
     */
    image?: string;
    /**
     * Tên tiếng việt của phân loại
     */
    gomdon_name?: string;
    height?: number;
    length?: number;
    /**
     * Tên tiếng việt của sản phẩm
     */
    gomdon_product_name?: string;
    width?: number;
    weight?: number;
    /**
     * Số lượng hàng có trong kho
     */
    stock?: number;
}

