/**
 * Gom Don API
 * Gom Don API.
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { BuyModelUpdateData } from './buyModelUpdateData';


export interface BuyModelUpdate { 
    /**
     * Id của document do mình quản lý
     */
    gomdon_id: string;
    data: BuyModelUpdateData;
}

