/**
 * Gom Don API
 * Gom Don API.
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface InlineObject2 { 
    uid: string;
    role: InlineObject2.RoleEnum;
}
export namespace InlineObject2 {
    export type RoleEnum = 'admin' | 'quanlykho' | 'kiemhang' | 'donghang' | 'quanlyCTVban' | 'quanlyCTVmua' | 'nguoimoi';
    export const RoleEnum = {
        Admin: 'admin' as RoleEnum,
        Quanlykho: 'quanlykho' as RoleEnum,
        Kiemhang: 'kiemhang' as RoleEnum,
        Donghang: 'donghang' as RoleEnum,
        QuanlyCTVban: 'quanlyCTVban' as RoleEnum,
        QuanlyCTVmua: 'quanlyCTVmua' as RoleEnum,
        Nguoimoi: 'nguoimoi' as RoleEnum
    };
}


