/**
 * Gom Don API
 * Gom Don API.
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { SellCreateReceiptOrders } from './sellCreateReceiptOrders';


export interface SellCreateReceipt { 
    bank: string;
    /**
     * Ngày tiền về ví
     */
    date_receive?: number;
    note?: string;
    orders: Array<SellCreateReceiptOrders>;
}

