/**
 * Gom Don API
 * Gom Don API.
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface SellCreateReceiptOrders { 
    /**
     * Mã đơn hàng
     */
    order_sn?: string;
    /**
     * Số tiền sàn trả
     */
    paid?: number;
    /**
     * Chênh lệch
     */
    offset?: number;
}

